name: 'admin-catalog-videos'

services:
  php:
    build: .
    container_name: admin-php
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - app-network

  nginx:
    image: 'nginx:latest'
    container_name: admin-nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge